# Generated by Django 4.2.7 on 2025-11-29 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='category name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('purchase', 'Purchase Receipt'), ('sale', 'Sales Order'), ('return_in', 'Sales Return'), ('return_out', 'Purchase Return'), ('adjustment', 'Stock Adjustment'), ('transfer_in', 'Transfer In'), ('transfer_out', 'Transfer Out')], max_length=20, verbose_name='transaction type')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='quantity')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='unit cost')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='total cost')),
                ('running_balance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='running balance')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='reference')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'Inventory Transaction',
                'verbose_name_plural': 'Inventory Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='product name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('sku', models.CharField(max_length=100, unique=True, verbose_name='SKU')),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, verbose_name='barcode')),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='cost price')),
                ('average_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='average cost')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='selling price')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='tax rate')),
                ('current_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='current stock')),
                ('reorder_point', models.DecimalField(decimal_places=2, default=10, max_digits=10, verbose_name='reorder point')),
                ('ai_suggested_reorder_point', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='AI suggested reorder point')),
                ('last_restocked', models.DateTimeField(blank=True, null=True, verbose_name='last restocked')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/', verbose_name='image')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_discontinued', models.BooleanField(default=False, verbose_name='discontinued')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory.category', verbose_name='category')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='companies.company', verbose_name='company')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['name'],
            },
        ),
    ]
