# Generated by Django 4.2.7 on 2025-11-29 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0003_initial'),
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierpayment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_payments', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='purchases.supplierinvoice', verbose_name='invoice'),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='purchases.supplier', verbose_name='supplier'),
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_invoices', to='companies.company', verbose_name='company'),
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_invoices', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_invoices', to='purchases.purchaseorder', verbose_name='purchase order'),
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='purchases.supplier', verbose_name='supplier'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='companies.company', verbose_name='company'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_items', to='inventory.product', verbose_name='product'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchases.purchaseorder', verbose_name='purchase order'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='companies.company', verbose_name='company'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='purchases.supplier', verbose_name='supplier'),
        ),
        migrations.AddField(
            model_name='goodsreceiptitem',
            name='goods_receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchases.goodsreceipt', verbose_name='goods receipt'),
        ),
        migrations.AddField(
            model_name='goodsreceiptitem',
            name='purchase_order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_items', to='purchases.purchaseorderitem', verbose_name='purchase order item'),
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_receipts', to='companies.company', verbose_name='company'),
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_receipts', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_receipts', to='purchases.purchaseorder', verbose_name='purchase order'),
        ),
        migrations.AlterUniqueTogether(
            name='supplierpayment',
            unique_together={('payment_number', 'company')},
        ),
        migrations.AlterUniqueTogether(
            name='supplierinvoice',
            unique_together={('invoice_number', 'company')},
        ),
        migrations.AlterUniqueTogether(
            name='supplier',
            unique_together={('name', 'company')},
        ),
        migrations.AlterUniqueTogether(
            name='purchaseorder',
            unique_together={('order_number', 'company')},
        ),
        migrations.AlterUniqueTogether(
            name='goodsreceiptitem',
            unique_together={('goods_receipt', 'purchase_order_item')},
        ),
        migrations.AlterUniqueTogether(
            name='goodsreceipt',
            unique_together={('receipt_number', 'company')},
        ),
    ]
