# Generated by Django 4.2.7 on 2025-11-29 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartOfAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='account code')),
                ('name', models.CharField(max_length=200, verbose_name='account name')),
                ('account_type', models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('equity', 'Equity'), ('revenue', 'Revenue'), ('expense', 'Expense')], max_length=20, verbose_name='account type')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'Chart of Accounts',
                'verbose_name_plural': 'Chart of Accounts',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='FinancialPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='period name')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(verbose_name='end date')),
                ('is_closed', models.BooleanField(default=False, verbose_name='closed')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'Financial Period',
                'verbose_name_plural': 'Financial Periods',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='FinancialStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_type', models.CharField(choices=[('income_statement', 'Income Statement'), ('balance_sheet', 'Balance Sheet'), ('cash_flow', 'Cash Flow Statement'), ('equity_statement', 'Statement of Changes in Equity')], max_length=30, verbose_name='statement type')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('content', models.TextField(verbose_name='content')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'Financial Statement',
                'verbose_name_plural': 'Financial Statements',
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_number', models.CharField(max_length=50, verbose_name='entry number')),
                ('date', models.DateField(verbose_name='entry date')),
                ('description', models.TextField(verbose_name='description')),
                ('reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='reference')),
                ('is_posted', models.BooleanField(default=False, verbose_name='posted')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='companies.company', verbose_name='company')),
            ],
            options={
                'verbose_name': 'Journal Entry',
                'verbose_name_plural': 'Journal Entries',
                'ordering': ['-date', '-entry_number'],
            },
        ),
        migrations.CreateModel(
            name='TrialBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='opening balance')),
                ('debit_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='debit total')),
                ('credit_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='credit total')),
                ('closing_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='closing balance')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trial_balances', to='accounting.chartofaccounts', verbose_name='account')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trial_balances', to='companies.company', verbose_name='company')),
                ('financial_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trial_balances', to='accounting.financialperiod', verbose_name='financial period')),
            ],
            options={
                'verbose_name': 'Trial Balance',
                'verbose_name_plural': 'Trial Balances',
            },
        ),
        migrations.CreateModel(
            name='JournalEntryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='description')),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='debit')),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='credit')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_items', to='accounting.chartofaccounts', verbose_name='account')),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounting.journalentry', verbose_name='journal entry')),
            ],
            options={
                'verbose_name': 'Journal Entry Item',
                'verbose_name_plural': 'Journal Entry Items',
            },
        ),
    ]
