# Generated by Django 4.2.7 on 2025-11-29 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_statements', to='companies.company', verbose_name='company'),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_statements', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='financial_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_statements', to='accounting.financialperiod', verbose_name='financial period'),
        ),
        migrations.AddField(
            model_name='financialperiod',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_periods', to='companies.company', verbose_name='company'),
        ),
        migrations.AddField(
            model_name='chartofaccounts',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='companies.company', verbose_name='company'),
        ),
        migrations.AddField(
            model_name='chartofaccounts',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='accounting.chartofaccounts', verbose_name='parent account'),
        ),
        migrations.AlterUniqueTogether(
            name='trialbalance',
            unique_together={('financial_period', 'account')},
        ),
        migrations.AlterUniqueTogether(
            name='journalentry',
            unique_together={('entry_number', 'company')},
        ),
        migrations.AlterUniqueTogether(
            name='financialstatement',
            unique_together={('financial_period', 'statement_type')},
        ),
        migrations.AlterUniqueTogether(
            name='financialperiod',
            unique_together={('company', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='chartofaccounts',
            unique_together={('code', 'company')},
        ),
    ]
