# Generated by Django 4.2.7 on 2025-11-29 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='company name')),
                ('commercial_register', models.CharField(blank=True, max_length=100, null=True, verbose_name='commercial register')),
                ('tax_register', models.CharField(blank=True, max_length=100, null=True, verbose_name='tax register')),
                ('country', models.CharField(choices=[('SA', 'Saudi Arabia'), ('EG', 'Egypt'), ('AE', 'United Arab Emirates'), ('KW', 'Kuwait'), ('BH', 'Bahrain'), ('QA', 'Qatar'), ('OM', 'Oman'), ('JO', 'Jordan'), ('LB', 'Lebanon'), ('IQ', 'Iraq')], max_length=2, verbose_name='country')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
                ('address', models.TextField(verbose_name='address')),
                ('phone', models.CharField(max_length=20, verbose_name='phone')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('website', models.URLField(blank=True, null=True, verbose_name='website')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/', verbose_name='logo')),
                ('zatca_enabled', models.BooleanField(default=False, verbose_name='ZATCA enabled')),
                ('zatca_certificate', models.TextField(blank=True, null=True, verbose_name='ZATCA certificate')),
                ('zatca_private_key', models.TextField(blank=True, null=True, verbose_name='ZATCA private key')),
                ('eta_enabled', models.BooleanField(default=False, verbose_name='ETA enabled')),
                ('eta_certificate', models.TextField(blank=True, null=True, verbose_name='ETA certificate')),
                ('eta_private_key', models.TextField(blank=True, null=True, verbose_name='ETA private key')),
                ('subscription_plan', models.CharField(default='basic', max_length=50, verbose_name='subscription plan')),
                ('subscription_expires', models.DateField(blank=True, null=True, verbose_name='subscription expires')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
    ]
