# Generated by Django 4.2.7 on 2025-11-29 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='customer name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='phone')),
                ('address', models.TextField(blank=True, null=True, verbose_name='address')),
                ('tax_register', models.CharField(blank=True, max_length=100, null=True, verbose_name='tax register')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='balance')),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='credit limit')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_type', models.CharField(choices=[('sales', 'Sales Invoice'), ('return', 'Sales Return'), ('quote', 'Sales Quote')], default='sales', max_length=20, verbose_name='invoice type')),
                ('invoice_number', models.CharField(max_length=50, verbose_name='invoice number')),
                ('date', models.DateField(verbose_name='invoice date')),
                ('due_date', models.DateField(verbose_name='due date')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='subtotal')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='tax amount')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='discount amount')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='total amount')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='paid amount')),
                ('payment_status', models.CharField(choices=[('paid', 'Paid'), ('partial', 'Partially Paid'), ('unpaid', 'Unpaid'), ('overdue', 'Overdue'), ('refunded', 'Refunded')], default='unpaid', max_length=20, verbose_name='payment status')),
                ('is_sent', models.BooleanField(default=False, verbose_name='sent')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('qr_code_data', models.TextField(blank=True, null=True, verbose_name='QR code data')),
                ('zatca_uuid', models.CharField(blank=True, max_length=100, null=True, verbose_name='ZATCA UUID')),
                ('zatca_hash', models.CharField(blank=True, max_length=500, null=True, verbose_name='ZATCA hash')),
                ('eta_uuid', models.CharField(blank=True, max_length=100, null=True, verbose_name='ETA UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'ordering': ['-date', '-invoice_number'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='description')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='unit price')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='discount percentage')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='tax rate')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='total')),
            ],
            options={
                'verbose_name': 'Invoice Item',
                'verbose_name_plural': 'Invoice Items',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount')),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('bank_transfer', 'Bank Transfer'), ('check', 'Check'), ('online', 'Online Payment')], max_length=20, verbose_name='payment method')),
                ('reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='reference')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('date', models.DateField(verbose_name='payment date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
